version: "3.3"
services:
  django_app:
    image: stock_market
    build: .
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./django-entrypoint.sh
    depends_on:
      - postgres_app
      - redis_app

  postgres_app:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  localstack_app:
    container_name: ${AWS_HOST}
    image: localstack/localstack
    env_file:
      - .env
    ports:
      - ${AWS_PORT}:4566
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DEBUG=0
    volumes:
      - ./localstack-entrypoint.sh:/etc/localstack/init/ready.d/localstack-entrypoint.sh

  redis_app:
    image: bitnami/redis:latest
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery_app:
    image: stock_market
    container_name: celery
    entrypoint:
      - ./celery-entrypoint.sh
    depends_on:
      - redis_app
      - django_app
