version: "3.3"
services:
  django_app:
    image: stock_market
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - postgres_app

  postgres_app:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
