version: "3.3"
services:
  django_app:
    image: stock_market
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - postgres_app

  postgres_app:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    env_file:
      - .env
    ports:
      - "${AWS_PORT}:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./localstack_entrypoint.sh:/etc/localstack/init/ready.d/localstack_entrypoint.sh
