version: "3.3"
services:
  django_app:
    image: stock_market
    build: .
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./django-entrypoint.sh
    depends_on:
      - postgres_app
      - redis_app

  postgres_app:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  localstack_app:
    container_name: ${AWS_HOST}
    image: localstack/localstack
    env_file:
      - .env
    ports:
      - ${AWS_PORT}:${AWS_PORT}
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DEBUG=0
    volumes:
      - ./localstack-entrypoint.sh:/etc/localstack/init/ready.d/localstack-entrypoint.sh

  redis_app:
    image: bitnami/redis:latest
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery_app:
    image: stock_market
    container_name: celery
    entrypoint:
      - ./celery-entrypoint.sh
    depends_on:
      - redis_app
      - django_app

  zookeeper_app:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: ${ZOOKEEPER_HOST}
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}

  kafka_app:
    image: confluentinc/cp-server:7.2.1
    container_name: ${KAFKA_HOST}
    depends_on:
      - zookeeper_app
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}:${ZOOKEEPER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:29092,PLAINTEXT_HOST://${KAFKA_HOST}:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}

  kafka_consumer_app:
    image: stock_market
    build: .
    container_name: kafka-consumer
    entrypoint:
      - ./kafka-consumer-entrypoint.sh
    depends_on:
      - kafka_app
      - django_app
