# Generated by Django 5.0 on 2023-12-13 07:52

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="logos/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stock", "stock"),
                            ("cryptocurrency", "cryptocurrency"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investment",
            },
        ),
        migrations.CreateModel(
            name="InvestmentPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("spend_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_subscribed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investment_portfolio",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="LimitOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("canceled", "canceled"),
                            ("deleted", "deleted"),
                            ("completed", "completed"),
                        ],
                        default="active",
                    ),
                ),
                ("is_sell", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "activated_status",
                    models.CharField(
                        choices=[
                            ("gte", "greater than or equal"),
                            ("lte", "less than or equal"),
                            ("gt", "greater then"),
                            ("lt", "less than"),
                            ("equal", "equal"),
                        ],
                        default="lte",
                    ),
                ),
            ],
            options={
                "db_table": "limit_order",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("canceled", "canceled"),
                            ("deleted", "deleted"),
                            ("completed", "completed"),
                        ],
                        default="active",
                    ),
                ),
                ("is_sell", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_order",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trade",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="investment",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", Decimal("0"))),
                name="investment_price_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="investmentportfolio",
            name="investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="brokers.investment"
            ),
        ),
        migrations.AddField(
            model_name="investmentportfolio",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="limitorder",
            name="investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="brokers.investment"
            ),
        ),
        migrations.AddField(
            model_name="limitorder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="brokers.investmentportfolio",
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="brokers.investment"
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="brokers.investmentportfolio",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="buyer",
                to="brokers.investmentportfolio",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="brokers.investment"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seller",
                to="brokers.investmentportfolio",
            ),
        ),
        migrations.AddConstraint(
            model_name="limitorder",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", Decimal("0"))),
                name="limit_order_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", Decimal("0"))),
                name="trade_price_non_negative",
            ),
        ),
    ]
