# Generated by Django 5.0 on 2023-12-22 17:15

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="limitorder",
            old_name="owner",
            new_name="portfolio",
        ),
        migrations.RenameField(
            model_name="marketorder",
            old_name="owner",
            new_name="portfolio",
        ),
        migrations.AlterUniqueTogether(
            name="investmentportfolio",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="limitorder",
            name="count",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="count",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="count",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentportfolio",
            constraint=models.CheckConstraint(
                check=models.Q(("spend_amount__gte", Decimal("0"))),
                name="investment_portfolio_spend_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="limitorder",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 1)),
                name="limit_order_count_greater_than_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketorder",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 1)),
                name="market_order_count_greater_than_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                check=models.Q(("count__gte", 1)), name="trade_count_greater_than_0"
            ),
        ),
    ]
