# Generated by Django 5.0 on 2023-12-19 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="limitorder",
            old_name="owner",
            new_name="portfolio",
        ),
        migrations.RenameField(
            model_name="marketorder",
            old_name="owner",
            new_name="portfolio",
        ),
    ]
