# Generated by Django 5.0 on 2023-12-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                check=models.Q(("seller", models.F("buyer")), _negated=True),
                name="trade_seller_not_equal_buyer",
            ),
        ),
    ]
