# Generated by Django 5.0 on 2023-12-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True, null=True, to="brokers.investment"
            ),
        ),
    ]
